# Generated by Django 4.0.2 on 2022-03-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('contact_person_name', models.CharField(blank=True, max_length=50)),
                ('mobile_number1', models.PositiveIntegerField(blank=True, default=0)),
                ('mobile_number2', models.PositiveIntegerField(blank=True, default=0)),
                ('email', models.EmailField(max_length=254)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.profile')),
            ],
        ),
    ]
