# Generated by Django 4.0.2 on 2022-03-20 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0002_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('monday_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('tuesday_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('tuesday_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('wednesday_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('wednesday_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('thrusday_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('thrusday_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('friday_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('friday_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('saturday_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('saturday_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('sunday_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('sunday_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('lunch_start_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('lunch_end_time', models.TimeField(default=datetime.datetime(2022, 3, 20, 13, 16, 0, 300614))),
                ('note', models.CharField(max_length=100)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.branches')),
            ],
        ),
    ]
