# Generated by Django 4.0.2 on 2022-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0003_office_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_hours',
            name='friday_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='friday_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='lunch_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='lunch_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='monday_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='monday_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='saturday_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='saturday_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='sunday_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='sunday_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='thrusday_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='thrusday_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='tuesday_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='tuesday_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='wednesday_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='office_hours',
            name='wednesday_start_time',
            field=models.TimeField(blank=True),
        ),
    ]
