# Generated by Django 4.0.2 on 2022-03-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0006_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agency_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.profile'),
        ),
    ]
