# Generated by Django 4.0.2 on 2022-03-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0007_alter_agents_agency_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='NRIC',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agents',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='uen',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
