# Generated by Django 4.0.2 on 2022-03-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0008_alter_agents_nric_alter_agents_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDWs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maid_name', models.CharField(blank=True, max_length=50)),
                ('maid_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('dob', models.DateField()),
                ('ref', models.CharField(max_length=50)),
                ('maid_type', models.CharField(max_length=20)),
                ('ethic_group', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20, null=True)),
                ('height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('weight', models.PositiveBigIntegerField(blank=True, null=True)),
                ('education', models.CharField(max_length=50)),
                ('no_of_sibling', models.PositiveBigIntegerField(blank=True, null=True)),
                ('no_of_children', models.PositiveBigIntegerField(blank=True, null=True)),
                ('martial_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ages_of_children', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('FIN', models.CharField(blank=True, max_length=50, null=True)),
                ('spoken_language', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.agents')),
            ],
        ),
    ]
