# Generated by Django 4.0.2 on 2022-03-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0010_alter_agents_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdws',
            name='FIN',
        ),
        migrations.RemoveField(
            model_name='mdws',
            name='gender',
        ),
    ]
