# Generated by Django 4.0.2 on 2022-03-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0011_remove_mdws_fin_remove_mdws_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(max_length=50)),
                ('passport_expiry_date', models.DateField()),
                ('malaysian_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('malaysian_id', models.CharField(blank=True, max_length=50, null=True)),
                ('imigration_pass_type', models.CharField(blank=True, max_length=50, null=True)),
                ('svp', models.CharField(blank=True, max_length=50, null=True)),
                ('work_permit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('work_permit_ep_date', models.DateField()),
                ('FIN', models.CharField(blank=True, max_length=50, null=True)),
                ('mdw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.mdws')),
            ],
        ),
    ]
