# Generated by Django 4.0.2 on 2022-03-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0012_immigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residential_address', models.CharField(blank=True, max_length=50, null=True)),
                ('airport', models.CharField(blank=True, max_length=50, null=True)),
                ('home_country', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_no', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_person_no_2', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mdw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.mdws')),
            ],
        ),
    ]
