# Generated by Django 4.0.2 on 2022-03-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0013_home_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mental_illness', models.BooleanField(blank=True, null=True)),
                ('epilepsy', models.BooleanField(blank=True, null=True)),
                ('asthma', models.BooleanField(blank=True, null=True)),
                ('diabetes', models.BooleanField(blank=True, null=True)),
                ('hyper_tension', models.BooleanField(blank=True, null=True)),
                ('tuberculosis', models.BooleanField(blank=True, null=True)),
                ('heart_disease', models.BooleanField(blank=True, null=True)),
                ('maleria', models.BooleanField(blank=True, null=True)),
                ('operations', models.BooleanField(blank=True, null=True)),
                ('allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_disabilities', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=100, null=True)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
                ('mdw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.mdws')),
            ],
        ),
    ]
