# Generated by Django 4.0.2 on 2022-03-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0014_medical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Willingness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_pork', models.BooleanField(blank=True, null=True)),
                ('eat_pork', models.BooleanField(blank=True, null=True)),
                ('handle_beef', models.BooleanField(blank=True, null=True)),
                ('eat_beef', models.BooleanField(blank=True, null=True)),
                ('care_pets', models.BooleanField(blank=True, null=True)),
                ('wash_car', models.BooleanField(blank=True, null=True)),
                ('gardening_works', models.BooleanField(blank=True, null=True)),
                ('mdw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.mdws')),
            ],
        ),
        migrations.CreateModel(
            name='Rest_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_no_of_rest_days', models.PositiveIntegerField()),
                ('willing_to_work_on_off_days', models.BooleanField(blank=True, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('mdw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.mdws')),
            ],
        ),
    ]
