# Generated by Django 4.0.2 on 2022-03-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0016_alter_mdws_country_alter_mdws_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigration',
            name='svp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
