# Generated by Django 4.0.2 on 2022-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0017_alter_immigration_svp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdws',
            name='maid_image',
            field=models.ImageField(blank=True, null=True, upload_to='MDWs/Images/'),
        ),
    ]
