# Generated by Django 4.0.2 on 2022-03-28 19:09

import Organisation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0019_alter_mdws_maid_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdws',
            name='maid_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=Organisation.models.MDWs_images_path_and_rename),
        ),
        migrations.AlterField(
            model_name='mdws',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to=Organisation.models.MDWs_images_path_and_rename),
        ),
    ]
