# Generated by Django 4.0.2 on 2022-03-28 19:12

import Organisation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0020_mdws_maid_image_2_alter_mdws_thumb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDWs_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('Doc', models.FileField(blank=True, null=True, upload_to=Organisation.models.MDWs_document_path_and_rename)),
                ('mdw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.mdws')),
            ],
        ),
    ]
