# Generated by Django 4.0.2 on 2022-03-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0021_fdws_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdws_documents',
            name='mdw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.mdws'),
        ),
    ]
