# Generated by Django 4.0.2 on 2022-03-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0022_alter_fdws_documents_mdw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='gender',
        ),
    ]
