# Generated by Django 4.0.2 on 2022-03-29 13:21

import Organisation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0024_alter_mdws_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=Organisation.models.Agents_images_path_and_rename),
        ),
    ]
