# Generated by Django 4.0.2 on 2022-03-29 13:53

import Organisation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0025_agents_gender_alter_agents_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('license', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Organisation.models.Agents_images_path_and_rename)),
                ('contact_person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_number', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='contact_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mdm', 'Mdm'), ('Dr', 'Dr')], max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('work_phone', models.PositiveIntegerField(blank=True, null=True)),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary', models.BooleanField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.agents_company')),
            ],
        ),
    ]
