# Generated by Django 4.0.2 on 2022-03-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0026_agents_company_alter_agents_agent_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='uen',
        ),
    ]
