# Generated by Django 4.0.2 on 2022-03-30 05:17

import Organisation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0027_remove_agents_uen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to=Organisation.models.Agent_document_path_and_rename)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.agents')),
            ],
        ),
    ]
