# Generated by Django 4.0.2 on 2022-03-30 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0028_agent_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_documents',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.agents_company'),
        ),
        migrations.AlterField(
            model_name='agent_documents',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.agents'),
        ),
    ]
