# Generated by Django 4.0.2 on 2022-04-03 08:37

import Organisation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0029_agent_documents_company_alter_agent_documents_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, default='Agency/images/blank_logo.png', null=True, upload_to=Organisation.models.Agency_images_path_and_rename),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, default='www.xyz.com', max_length=50, null=True),
        ),
    ]
