# Generated by Django 4.0.2 on 2022-04-03 10:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0031_alter_branches_address_alter_branches_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='mobile_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=0, max_length=128, null=True, region=None),
        ),
    ]
