# Generated by Django 4.0.2 on 2022-04-03 10:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0034_alter_profile_contact_person_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='contact_person_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=0, max_length=128, null=True, region=None),
        ),
    ]
