# Generated by Django 4.0.2 on 2022-04-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0039_alter_agents_contact_person_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents_company',
            name='contact_person_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branches',
            name='mobile_number1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='branches',
            name='mobile_number2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contact_list',
            name='mobile_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home_country',
            name='contact_person_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home_country',
            name='contact_person_no_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
