# Generated by Django 4.0.2 on 2022-04-10 08:28

import Organisation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0040_alter_agents_company_contact_person_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=50)),
                ('Emp_id', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to=Organisation.models.Staff_images_path_and_rename)),
                ('Registration', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organisation.profile')),
            ],
        ),
    ]
