# Generated by Django 4.0.2 on 2022-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0042_rename_agency_username_staff_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='NRIC',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
