# Generated by Django 4.0.2 on 2022-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0043_staff_nric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
