# Generated by Django 4.0.2 on 2022-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0045_rename_staff_agency_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency_staff',
            name='staff_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
