# Generated by Django 4.0.2 on 2022-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0046_alter_agency_staff_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency_staff',
            name='NRIC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
