# Generated by Django 4.0.2 on 2022-04-12 06:56

import Organisation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0048_staff_documents'),
    ]

    operations = [
        
    ]
