# Generated by Django 4.0.2 on 2022-04-21 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0050_remove_staff_documents_agency_staff_documents_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdws',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.agents_company'),
        ),
    ]
