# Generated by Django 4.0.2 on 2022-04-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0051_mdws_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_country',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
