# Generated by Django 4.0.2 on 2022-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0052_alter_home_country_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_hours',
            name='monday_start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
