# Generated by Django 4.0.2 on 2022-04-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0053_alter_office_hours_monday_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_hours',
            name='Branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.branches'),
        ),
    ]
