# Generated by Django 4.0.2 on 2022-04-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0054_alter_office_hours_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organisation.profile'),
        ),
    ]
