# Generated by Django 4.0.2 on 2022-04-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0055_alter_social_media_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_hours',
            name='monday_start_time',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
    ]
