# Generated by Django 4.0.2 on 2022-03-17 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgencyProfile',
            new_name='AgencyDetails',
        ),
    ]
