# Generated by Django 4.0.2 on 2022-03-17 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agency', '0002_rename_agencyprofile_agencydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=50)),
                ('license_no', models.CharField(max_length=20)),
                ('uen', models.PositiveIntegerField()),
                ('gst_registration', models.CharField(max_length=20)),
                ('sub_domain_url', models.CharField(max_length=50)),
                ('fiscal_year', models.DateField()),
                ('address', models.CharField(blank=True, max_length=100)),
                ('contact_person_name', models.CharField(blank=True, max_length=50)),
                ('contact_person_number', models.PositiveIntegerField(blank=True, default=12)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AgencyDetails',
        ),
    ]
