from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Profile)
admin.site.register(Branches)
admin.site.register(Office_hours)
admin.site.register(Agents)
admin.site.register(MDWs)
admin.site.register(Immigration)
admin.site.register(Willingness)
admin.site.register(Home_country)
admin.site.register(Rest_days)
admin.site.register(Medical)
admin.site.register(FDWs_Documents)
admin.site.register(Agents_company)
admin.site.register(contact_list)
admin.site.register(Agent_Documents)
admin.site.register(Agency_staff)
admin.site.register(Staff_Documents)
admin.site.register(Agency_Documents)
admin.site.register(social_media)